// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFy57CI5Bs1eiuK4FiaBUT1b-aPUZT4ts',
    appId: '1:813874496524:web:c602161499425c81bf5a29',
    messagingSenderId: '813874496524',
    projectId: 'neighbourhood-hub-bbb75',
    authDomain: 'neighbourhood-hub-bbb75.firebaseapp.com',
    storageBucket: 'neighbourhood-hub-bbb75.firebasestorage.app',
    measurementId: 'G-JRBMYZ9ZN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNEkjIXWZq-9KwcJsSM0xhndcF2rt4zdQ',
    appId: '1:813874496524:android:9b2924b6c298b4bdbf5a29',
    messagingSenderId: '813874496524',
    projectId: 'neighbourhood-hub-bbb75',
    storageBucket: 'neighbourhood-hub-bbb75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_SEh9BXhzPtqznVF2HRoGTqA46uKWP5A',
    appId: '1:813874496524:ios:5701e0340fa189e0bf5a29',
    messagingSenderId: '813874496524',
    projectId: 'neighbourhood-hub-bbb75',
    storageBucket: 'neighbourhood-hub-bbb75.firebasestorage.app',
    iosBundleId: 'com.example.hemisphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFy57CI5Bs1eiuK4FiaBUT1b-aPUZT4ts',
    appId: '1:813874496524:web:da5ea3b545dee471bf5a29',
    messagingSenderId: '813874496524',
    projectId: 'neighbourhood-hub-bbb75',
    authDomain: 'neighbourhood-hub-bbb75.firebaseapp.com',
    storageBucket: 'neighbourhood-hub-bbb75.firebasestorage.app',
    measurementId: 'G-PPM9MQTJ1X',
  );
}
